language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-19.0.0
    - android-20

env:
  matrix:
    - ANDROID_TARGET=android-20
    - ANDROID_ABI=armeabi-v7a

before_script:
  - chmod +x gradlew

script:
  -
  - ./gradlew assemble
  - ./gradlew test