language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-20.0.0
    - android-20
    - extra-android-support
    - extra-android-m2repository

env:
  matrix:
    - ANDROID_TARGET=android-20
    - ANDROID_ABI=armeabi-v7a

before_script:
  - chmod +x gradlew

script:
  -
  - ./gradlew assemble
  - ./gradlew test